### PR TITLE
Try to use token from env var to make authenticated requests

### PR DESCRIPTION
**Pull request by aluxian**

### CODE REVIEW

**Comment by aluxian** [comment]
Hey @smebberson, can you please review (and publish) this when you have some time? Thanks!

**Comment by smebberson** [comment]
Looks good to me. I'll merge now and publish now.

**Comment by smebberson** [comment]
@Aluxian, I can't publish to `npm` right now (https://github.com/npm/npm/issues/11422). Hopefully soon!

**Comment by smebberson** [comment]
@Aluxian, published on `npm` now! Thanks for the PR.

**Comment by aluxian** [comment]
Great, thanks! :+1:

**Pull request merged**
